Repository mcci-catena/Catena-Arduino-Platform, pull requests merged in 2019-07, with the labels that each got.

#174 Fix #135: Added the Platform support for Catena 4630/4617/4618
  .travis.yml
  README.md
  src/Catena.h
  src/Catena4617.h
  src/Catena4618.h
  src/Catena4630.h
  src/Catena463x.h
  src/CatenaBase.h
  src/Catena_Guids.h
  src/Catena_Platforms.h
  src/lib/stm32/catena461x/Catena4617_ReadVoltage.cpp
  src/lib/stm32/catena461x/Catena4617_getPlatformTable.cpp
  src/lib/stm32/catena461x/Catena4618_ReadVoltage.cpp
  src/lib/stm32/catena461x/Catena4618_getPlatformTable.cpp
  src/lib/stm32/catena463x/Catena4630_ReadVoltage.cpp
  src/lib/stm32/catena463x/Catena4630_getPlatformTable.cpp
  src/lib/stm32/catena463x/Catena463x_LoRaWAN_begin.cpp
  src/lib/stm32/catena463x/Catena463x_begin.cpp
Labels: enhancement

#181 Fix #180: prepare release v0.15.0
  README.md
  VERSION.txt
  library.properties
  src/CatenaBase.h
Labels: release

#186 Fix #185, and improve CI
  .travis.yml
  src/Catena_Log.h
Labels: bug, travis

#188 Fix #187: use standard way to select au921
  .travis.yml
Labels: travis

#193 Major doc improvement; add cFSM<>
  .travis.yml
  README.md
  assets/Catena_LoRaWAN.plantuml
  assets/Catena_PollableInterface.plantuml
  assets/FSMexample.plantuml
  examples/catena_fsm/catena_fsm.ino
  examples/catena_usercommand/catena_usercommand.ino
  src/Catena_FSM.h
Labels: docs, enhancement

#195 Fix #194: prepare for release v0.16.0
  README.md
  VERSION.txt
  library.properties
  src/CatenaBase.h
Labels: release

#200 Fix #199: extract key-making script to own file, update comments
  extra/make-lorawan-keys-entry.sh
  src/lib/samd/catena4410/Catena4410_gk_lorawan_keys.cpp
  src/lib/samd/catena4420/Catena4420_gk_lorawan_keys.cpp
Labels: bug, enhancement

#201 Fix issue 129; check RTC clock source and set prescaler value
  src/CatenaSamd21.h
  src/CatenaStm32L0.h
  src/lib/stm32/stm32l0/CatenaStm32L0Rtc.cpp
Labels: bug

#203 Add system clock calibration support
  README.md
  src/CatenaBase.h
  src/CatenaStm32L0.h
  src/lib/CatenaBase_registerCommands.cpp
  src/lib/stm32/stm32l0/CatenaStm32L0_CalibrateSystemClock.cpp
  src/lib/stm32/stm32l0/CatenaStm32L0_GetSystemClockRate.cpp
  src/lib/stm32/stm32l0/CatenaStm32L0_LoRaWAN_begin.cpp
  src/lib/stm32/stm32l0/CatenaStm32L0_begin.cpp
  src/lib/stm32/stm32l0/CatenaStm32L0_registerCommands.cpp
Labels: bug

#206 Fix #205: prepare to release v0.17.0
  README.md
  VERSION.txt
  library.properties
  src/CatenaBase.h
Labels: release
